// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/netball-layouts/CardDeck.tsx": () => import("../components/mockups/netball-layouts/CardDeck.tsx"),
  "./components/mockups/netball-layouts/HeroZone.tsx": () => import("../components/mockups/netball-layouts/HeroZone.tsx"),
  "./components/mockups/netball-layouts/SidebarNavigator.tsx": () => import("../components/mockups/netball-layouts/SidebarNavigator.tsx")
};
